# =============================================================================
# analytics.py — Reporting utilities for NoQ.
#
# Reads the served_count and total_wait_time_sum accumulators maintained by
# QueueManager and returns services ranked by average wait time (descending).
# Used by the /api/analytics endpoint in app.py and the CLI.
# =============================================================================

from typing import List, Tuple
from .queues import QueueManager

# AI-generated: This function was initially generated by GitHub Copilot from
# the prompt "rank services by average wait time using served_count and
# total_wait_time_sum dictionaries", then reviewed and adjusted by hand.
def rank_services_by_avg_wait(manager: QueueManager) -> List[Tuple[str, float]]:
    """
    O(n log n) - Ranks services by average wait time (descending).
    
    Why O(n log n)?
    - Iterating services is O(n)
    - Python's generic sort (Timsort) is O(n log n)
    """
    stats = []
    
    # O(n) to build the list
    for service, count in manager.served_count.items():
        total_time = manager.total_wait_time_sum.get(service, 0.0)
        avg_wait = total_time / count if count > 0 else 0.0
        stats.append((service, avg_wait))
    
    # O(n log n) to sort
    # Sort by avg_wait descending
    stats.sort(key=lambda x: x[1], reverse=True)
    
    return stats
